### ISSUE TITLE
Support for disposable shards

### ISSUE THREAD

**Issue by Protonull** [DevotedMC/Zeus#5]
There have been a few discussions about mini-games and such that would take place in disposable shards. Obviously this is not an immediate concern with the release date looming, but it's something that should be kept in mind, hence the issue :) For disposable shards to work, the following would need to be accommodated if they aren't already:

* **Dynamic shards and worlds**
 Meaning that which shard or world within a shard to send players to is decided programmatically rather than through configs.

* **Shard-origin**
 Shards receiving player transfers should know what shard the player is coming from and some basic details like what type of shard. This is primarily so the shard can send them back, like exiting a dungeon, arena, or battleground.

* **Non-editing transfers**
 Allow shards to send players to other shards without the prerequisite sending of player-data. For example, say you have a duelling shard, that after a long and bloody fight and you've won/lost and are teleported out of the shard, your nearly broken gear should reset to what it was before you entered the duel, because the duelling shard isn't imposing player-data upon the recipient shard; that the duelling is readonly, or rather, non-persistent.

* **Arbitrary player-data**
 You may wish to send arbitrary data along with or in lieu of full player-data, like for example advancement criteria. Say you have an achievement of winning 10 duels, but you also want the duelling shard to be "readonly" as mentioned above, then you need a way of notifying the other shards that the player won or lost etc.

**Comment by Maxopoly** [comment]
>  Meaning that which shard or world within a shard to send players to is decided programmatically rather than through configs.

Yes, ikely need a Zeus plugin which will handle the logic around instanciating and destroying these

> Shards receiving player transfers should know what shard the player is coming from and some basic details like what type of shard. This is primarily so the shard can send them back, like exiting a dungeon, arena, or battleground.

Shards can not decide where a player goes, anything like that is handled in Zeus. That being said, we can add a previous server field to server join requests

> Allow shards to send players to other shards without the prerequisite sending of player-data

So one thing I want to do is having different sets of player data, each with a different identifier. Non-editing transfer could be to just save the state you initially receive, though that means that any further changes made to player settings etc. are not possible.



> You may wish to send arbitrary data along with or in lieu of full player-data, like for example advancement criteria. Say you have an achievement of winning 10 duels, but you also want the duelling shard to be "readonly" as mentioned above, then you need a way of notifying the other shards that the player won or lost etc.

Partially solved through player settings api in CMC which allows writing arbitrary persistent data to the player. More complex relational constructs should be handled through a Zeus plugin, shards do not talk to each other directly in this architecture

**Comment by Protonull** [comment]
Going through some old issues: having given this some consideration, it's likely that allowing for disposable shards would first require an overhaul to Zeus to strip out some of the base assumptions of its usage that were added as part of the development for Devoted Hell. In my humble opinion, Zeus ought to be the means to move players between servers with persistent data, and Zeus already does that, but there are assumptions baked into Zeus about how that happens and why. Zeus was made to split a single world into four shards traversable by simply walking across a shard-border. But what if you don't want that? What if you want separate worlds/dimensions as shards? Or what if you want disposable shards? For Zeus to progress as a general purpose sharding solution, it needs to be stripped of its one-world-many-shards assumptions, which can be re-added as a Zeus plugin.
